---
title: "单个元音选择次数-特殊个体"
output: html_notebook
---
一些被试没有在格子里有重复选择，因此不适用原有程序

1. 配置分析环境
```{r}
options(digits = 0)
library(colorspace)
library(tidyverse)
library(stringr)

preProcess_cn_ihiy <- function(filename){
  cn_ihiy <- read.csv(filename, header = T)
  cn_ihiy <- select(cn_ihiy,answer1.SubTrial.,answer2.SubTrial.,starts_with("sound"))
  names(cn_ihiy)[1] <- "answer"
  names(cn_ihiy)[2] <- "rate"
  cn_ihiy$rate <- stringr::str_sub(cn_ihiy$rate, start = 2, end = -1)
  cn_ihiy <- unite(cn_ihiy, col = sound, sound111, sound112, sound113, sound114, sound115, sound121, sound122, sound123, sound124, sound125)
  cn_ihiy <- na.omit(cn_ihiy)
  cn_ihiy$sound <- str_extract(cn_ihiy$sound, pattern = "F1_..-F2_..")
  cn_ihiy <- separate(cn_ihiy, col = sound, into = c("X","Y"), sep = "-")
  cn_ihiy$X <- as.numeric(str_replace(cn_ihiy$X, pattern = "F1_", replacement = ""))
  cn_ihiy$Y <- as.numeric(str_replace(cn_ihiy$Y, pattern = "F2_", replacement = ""))
  cn_ihiy <- na.omit(cn_ihiy)
  cn_ihiy[cn_ihiy == ""] <- NA
  return(cn_ihiy)
}

preProcess_ihiy <- function(filename){
  en_ihiy <- read.csv(filename, header = T)
  en_ihiy <- select(en_ihiy,answer1.SubTrial.,answer2.SubTrial.,starts_with("sound"))
  names(en_ihiy)[1] <- "answer"
  names(en_ihiy)[2] <- "rate"
  en_ihiy$rate <- stringr::str_sub(en_ihiy$rate, start = 2, end = -1)
  en_ihiy <- unite(en_ihiy, col = sound, sound111, sound112, sound113, sound114, sound115, sound121, sound122, sound123, sound124, sound125)
  en_ihiy <- na.omit(en_ihiy)
  en_ihiy$sound <- str_extract(en_ihiy$sound, pattern = "F1_..-F2_..")
  en_ihiy <- separate(en_ihiy, col = sound, into = c("X","Y"), sep = "-")
  en_ihiy$X <- as.numeric(str_replace(en_ihiy$X, pattern = "F1_", replacement = ""))
  en_ihiy$Y <- as.numeric(str_replace(en_ihiy$Y, pattern = "F2_", replacement = ""))
  en_ihiy <- na.omit(en_ihiy)
  return(en_ihiy)
}
```

2. 读取数据并分析

选择处理的音节是中文还是英文
```{r}
#输入要分析的音节是中文还是英文
file_type <- "EN"
if(file_type == "EN"){
  mydata_raw <- preProcess_ihiy(file.choose())
}else{
  mydata_raw <- preProcess_cn_ihiy(file.choose())
}
```

选择要处理的词汇
**请注意除了修改第63行，还需要修改67、68行中的词汇***
```{r}
need_analysis <- "hid"
mydata <- mydata_raw %>% 
  filter(answer == need_analysis) 
mydata$rate[!stringr::str_detect(mydata$rate, pattern = "[12345]")] <- NA
mydata <- na.omit(mydata)

mydata %>% 
  filter(rate == max(rate)) -> max_co
max_co
max_co <- cbind(max_co, 1)
names(max_co)[names(max_co) == 1] <- "MAX"
test <- left_join(mydata, max_co)

#绘图
p <- ggplot(test, aes(x = X, y = Y)) + geom_tile(colour = "grey50",fill = "white") + geom_tile(aes(fill = MAX)) + geom_text(aes(label = rate), size = 3) + theme_bw() + scale_fill_continuous(low = "#F8F8FF", high = "#FFFF00") + coord_equal(ratio = 1) + xlim(0,17) + ylim(0,20) + theme(panel.grid = element_blank())

print(p)

ggsave("D:/picture.png", p, dpi = 300, width = 10)
```


