---
title: "多个体数据平均程序"
output: html_notebook
---
编写处理工具函数
```{r}
preProcess_nv <- function(filename){
  require(tidyverse)
  require(stringr)
  en_nv <- read.csv(filename, header = T)
  en_nv <- select(en_nv, answer1.Block., sound111, sound112)
  names(en_nv)[1] <- "answer"
  en_nv <- unite(en_nv, sound, sound111, sound112)
  en_nv <- na.omit(en_nv)
  en_nv$sound <- str_extract(en_nv$sound, pattern = "(w|h).*d")
  en_nv <- mutate(en_nv, match = sound == answer)
  en_nv <- na.omit(en_nv)
  return(en_nv)
}

preProcess_ihiy <- function(filename){
  en_ihiy <- read.csv(filename, header = T)
  en_ihiy <- select(en_ihiy,answer1.SubTrial.,answer2.SubTrial.,starts_with("sound"))
  names(en_ihiy)[1] <- "answer"
  names(en_ihiy)[2] <- "rate"
  en_ihiy$rate <- stringr::str_sub(en_ihiy$rate, start = 2, end = -1)
  en_ihiy <- unite(en_ihiy, col = sound, sound111, sound112, sound113, sound114, sound115, sound121, sound122, sound123, sound124, sound125)
  en_ihiy <- na.omit(en_ihiy)
  en_ihiy$sound <- str_extract(en_ihiy$sound, pattern = "F1_..-F2_..")
  en_ihiy <- separate(en_ihiy, col = sound, into = c("X","Y"), sep = "-")
  en_ihiy$X <- as.numeric(str_replace(en_ihiy$X, pattern = "F1_", replacement = ""))
  en_ihiy$Y <- as.numeric(str_replace(en_ihiy$Y, pattern = "F2_", replacement = ""))
  en_ihiy <- na.omit(en_ihiy)
  return(en_ihiy)
}

combine_nv <- function(all_filenames){

  for(i in all_filenames){
    filelist[which(all_filenames == i)] <- preProcess_nv(i)
  }
}

combine_ihiy <- function(all_filenames){
  for
}

mean_single <- function(filename, words){
  mydata <- preProcess_ihiy(filename) %>% 
    filter(answer == words[1]|answer == words[2]|answer == words[3]|answer == words[4])

  result_mean_single <- c(0,0,0,0)
  
  names(result) <- c("answer", "rate", "X", "Y")
  for(i in unique(mydata$X)){
    for(j in unique(mydata$Y)){
      cheak_table <- mydata %>% 
        filter(X == i, Y == j, rate > 0) %>% 
        group_by(answer) %>% 
        summarise(count = nrow(.),mean = mean(as.numeric(as.character(rate))))
      if(nrow(cheak_table) != 0){
        result <- c(0,0,0,0)
        line_num <- which(cheak_table$count == max(cheak_table$count))
        if(length(line_num) == 1){
          result[1] <- as.character(unlist(cheak_table[line_num, 1]))
          result[2] <- cheak_table[line_num, 3]
          result[3] <- i
          result[4] <- j
          result_mean_single <- rbind(result_mean_single, result)
        }else{
          line_num <- which(cheak_table$mean == max(cheak_table$mean))
          result[1] <- as.character(unlist(cheak_table[line_num, 1]))
          result[2] <- cheak_table[line_num, 3]
          result[3] <- i
          result[4] <- j
          result_mean_single <- rbind(result_mean_single, result)
        }
      }else{next()}
    }
  }
  
  rownames(result_mean_single) <- NULL
  return(result_mean_single[-1,])
}
```


```{r}
filenames <- dir("sub-data/四个人的数据/", recursive = T)
if(sum(str_detect(filenames, pattern = "ihiy.*csv")) > 0){
  combine_ihiy(filenames[str_detect(filenames, pattern = "ihiy.*csv")])
}else{
  combine_nv(filenames[str_detect(filenames, pattern = "nv.*csv")])
}
```

