---
title: "汉语统计与绘图程序"
author: "夏骁凯"
date: "2017/1/13"
output: html_documcnt
---

对汉语的实验结果，进行统计并分析
```{r}
#配置分析环境
library(tidyverse)
library(colorspace)
library(stringr)
mixcolorhcl <- function(first, second) {
  hex(mixcolor(alpha = 0.5, 
               color1 = hex2RGB(first), color2 = hex2RGB(second)))
}    #混色函数

#导入实验数据
cn_nv_path <- file.choose()
cn_ihiy_path <- file.choose()
cn_nv <- read.csv(cn_nv_path, header = T)
cn_ihiy <- read.csv(cn_ihiy_path, header = T)

#对数据进行初步筛选与整理
cn_nv <- select(cn_nv, answer1.Block., sound111, sound112)
cn_nv <- unite(cn_nv, sound, sound111, sound112)
cn_ihiy <- select(cn_ihiy, answer1.SubTrial.,answer2.SubTrial.,starts_with("sound"))

names(cn_nv)[1] <- "answer"
names(cn_ihiy)[1] <- "answer"
names(cn_ihiy)[2] <- "rate"

#清除缺失值
cn_nv <- na.omit(cn_nv)

#对数据中的文件路径含义进行修改

#将实验1的文件路径改为对应单词，并确认是否匹配
cn_nv$answer[cn_nv$answer == "v"] <- "y"
cn_ihiy$answer[cn_ihiy$answer == "v"] <- "y"
cn_nv$sound <- str_sub(str_extract(cn_nv$sound, pattern = ".1"), start = 1, end = -2)
cn_nv <- mutate(cn_nv, matcn = sound == answer)
table(cn_nv$matcn, cn_nv$sound)

#复杂频数表
# ftable实现
ftable(cn_nv, row.vars = c(1,3), col.vars = 2)
```


```{r}
#绘制单音节图
cn_ihiy <- select(cn_ihiy,answer,rate,starts_with("sound"))
cn_ihiy <- unite(cn_ihiy, col = sound, sound111, sound112, sound113, sound114, sound115, sound121, sound122, sound123, sound124, sound125)
cn_ihiy <- na.omit(cn_ihiy)
cn_ihiy$sound <- str_extract(cn_ihiy$sound, pattern = "F1_..-F2_..")
cn_ihiy <- separate(cn_ihiy, col = sound, into = c("X","Y"), sep = "-")
cn_ihiy$X <- as.numeric(str_replace(cn_ihiy$X, pattern = "F1_", replacement = ""))
cn_ihiy$Y <- as.numeric(str_replace(cn_ihiy$Y, pattern = "F2_", replacement = ""))

cn_ihiy_i <- filter(cn_ihiy, answer == "i")
cn_ihiy_i <- reshape2::dcast(cn_ihiy_i[,c(1,3,4)], X + Y ~ answer)
ggplot(cn_ihiy_i, aes(x = X, y = Y, fill = i)) + geom_tile() + scale_fill_continuous() +theme_bw() + coord_equal(ratio=1)
```