---
title: "特定条件下heed，hid以及汉语元音li的热点图"
output: html_notebook
---
1. 配置分析环境
```{r}
options(digits = 0)
library(colorspace)
library(tidyverse)
library(stringr)

preProcess_cn_ihiy <- function(filename){
  cn_ihiy <- read.csv(filename, header = T)
  cn_ihiy <- select(cn_ihiy,answer1.SubTrial.,answer2.SubTrial.,starts_with("sound"))
  names(cn_ihiy)[1] <- "answer"
  names(cn_ihiy)[2] <- "rate"
  cn_ihiy$rate <- stringr::str_sub(cn_ihiy$rate, start = 2, end = -1)
  cn_ihiy <- unite(cn_ihiy, col = sound, sound111, sound112, sound113, sound114, sound115, sound121, sound122, sound123, sound124, sound125)
  cn_ihiy <- na.omit(cn_ihiy)
  cn_ihiy$sound <- str_extract(cn_ihiy$sound, pattern = "F1_..-F2_..")
  cn_ihiy <- separate(cn_ihiy, col = sound, into = c("X","Y"), sep = "-")
  cn_ihiy$X <- as.numeric(str_replace(cn_ihiy$X, pattern = "F1_", replacement = ""))
  cn_ihiy$Y <- as.numeric(str_replace(cn_ihiy$Y, pattern = "F2_", replacement = ""))
  cn_ihiy <- na.omit(cn_ihiy)
  cn_ihiy[cn_ihiy == ""] <- NA
  return(cn_ihiy)
}

preProcess_ihiy <- function(filename){
  en_ihiy <- read.csv(filename, header = T)
  en_ihiy <- select(en_ihiy,answer1.SubTrial.,answer2.SubTrial.,starts_with("sound"))
  names(en_ihiy)[1] <- "answer"
  names(en_ihiy)[2] <- "rate"
  en_ihiy$rate <- stringr::str_sub(en_ihiy$rate, start = 2, end = -1)
  en_ihiy <- unite(en_ihiy, col = sound, sound111, sound112, sound113, sound114, sound115, sound121, sound122, sound123, sound124, sound125)
  en_ihiy <- na.omit(en_ihiy)
  en_ihiy$sound <- str_extract(en_ihiy$sound, pattern = "F1_..-F2_..")
  en_ihiy <- separate(en_ihiy, col = sound, into = c("X","Y"), sep = "-")
  en_ihiy$X <- as.numeric(str_replace(en_ihiy$X, pattern = "F1_", replacement = ""))
  en_ihiy$Y <- as.numeric(str_replace(en_ihiy$Y, pattern = "F2_", replacement = ""))
  en_ihiy <- na.omit(en_ihiy)
  return(en_ihiy)
}
```

2. 读取数据并分析

选择处理的音节是中文还是英文
```{r}
#输入要分析的音节是中文还是英文
file_type <- "EN"
if(file_type == "EN"){
  mydata <- preProcess_ihiy(file.choose())
}else{
  mydata <- preProcess_cn_ihiy(file.choose())
}
```

选择要分析的词汇(注意要修改61与67行)
```{r}
need_analysis <- "heed"
mydata %>% 
  filter(answer == need_analysis) %>% 
  reshape2::dcast(X + Y ~ answer) -> data_table

data_table %>% 
  filter(heed >= 5) -> sig_table

count <- nrow(sig_table)
cat("符合条件的共有",count,"个")

sig_table <- cbind(sig_table,1)
names(sig_table)[names(sig_table) == 1] <- "count"

data_table <- left_join(data_table, sig_table)
#data_table$count[is.na(data_table$count)] <- 0

p <- ggplot(data_table, aes(x = X, y = Y)) + geom_tile(aes(fill = count), show.legend = F) + theme_bw(base_size = 18) + coord_equal(ratio = 1) + xlim(0,16) + ylim(0,20) + theme(panel.grid = element_blank())
print(p)
```

