---
title: "英语音节心理声学研究热点图程序"
author: "夏骁凯"
documentclass: ctexart
output:
  html_document: default
  html_notebook: default
  rticles::ctex:
    fig_caption: yes
    number_sections: yes
    toc: yes
classoption: hyperref,
---
1. 配置分析环境，构建分析函数
```{r}
options(digits = 2)
library(colorspace)
library(tidyverse)
library(stringr)

preProcess_nv <- function(filename){
  require(tidyverse)
  require(stringr)
  en_nv <- read.csv(filename, header = T)
  en_nv <- select(en_nv, answer1.Block., sound111, sound112)
  names(en_nv)[1] <- "answer"
  en_nv <- unite(en_nv, sound, sound111, sound112)
  en_nv <- na.omit(en_nv)
  en_nv$sound <- str_extract(en_nv$sound, pattern = "(w|h).*d")
  en_nv <- mutate(en_nv, match = sound == answer)
  en_nv <- na.omit(en_nv)
  return(en_nv)
}

preProcess_ihiy <- function(filename){
  en_ihiy <- read.csv(filename, header = T)
  en_ihiy <- select(en_ihiy,answer1.SubTrial.,answer2.SubTrial.,starts_with("sound"))
  names(en_ihiy)[1] <- "answer"
  names(en_ihiy)[2] <- "rate"
  en_ihiy$rate <- stringr::str_sub(en_ihiy$rate, start = 2, end = -1)
  en_ihiy <- unite(en_ihiy, col = sound, sound111, sound112, sound113, sound114, sound115, sound121, sound122, sound123, sound124, sound125)
  en_ihiy <- na.omit(en_ihiy)
  en_ihiy$sound <- str_extract(en_ihiy$sound, pattern = "F1_..-F2_..")
  en_ihiy <- separate(en_ihiy, col = sound, into = c("X","Y"), sep = "-")
  en_ihiy$X <- as.numeric(str_replace(en_ihiy$X, pattern = "F1_", replacement = ""))
  en_ihiy$Y <- as.numeric(str_replace(en_ihiy$Y, pattern = "F2_", replacement = ""))
  en_ihiy <- na.omit(en_ihiy)
  return(en_ihiy)
}

combine_nv <- function(all_filenames){

  for(i in all_filenames){
    filelist[which(all_filenames == i)] <- preProcess_nv(i)
  }
}

mean_single <- function(filename, words){
  mydata <- preProcess_ihiy(filename) %>% 
    filter(answer == words[1]|answer == words[2]|answer == words[3]|answer == words[4])

  result_mean_single <- c(0,0,0,0)
  result <- c(0,0,0,0)
  names(result) <- c("answer", "rate", "X", "Y")
  for(i in unique(mydata$X)){
    for(j in unique(mydata$Y)){
      cheak_table <- mydata %>% 
        filter(X == i, Y == j, rate > 0) %>% 
        group_by(answer) %>% 
        summarise(count = nrow(.),mean = mean(as.numeric(as.character(rate))))
          result <- c(0,0,0,0)
      if(nrow(cheak_table) != 0){
        line_num <- which(cheak_table$count == max(cheak_table$count))
        if(length(line_num) == 1){
          result[1] <- as.character(unlist(cheak_table[line_num, 1]))
          result[2] <- cheak_table[line_num, 3]
          result[3] <- i
          result[4] <- j
          result_mean_single <- rbind(result_mean_single, result)
        }else{
          line_num <- which(cheak_table$mean == max(cheak_table$mean))
          result[1] <- as.character(unlist(cheak_table[line_num, 1]))
          result[2] <- cheak_table[line_num, 3]
          result[3] <- i
          result[4] <- j
          result_mean_single <- rbind(result_mean_single, result)
        }
      }else{next()}
    }
  }
  rownames(result_mean_single) <- NULL
  colnames(result_mean_single) <- c("answer", "rate", "X", "Y")
  return(result_mean_single[-1,])
}

#色彩渐变比例尺
color <- sequential_hcl(10, h = 60, c = c(100, 30), l = c(50, 90))
colortable <- data.frame(x = 1:10, y = 1, color = color) #构造绘图函数
names(color) <- factor(10:1) #构造色彩映射
ggplot(colortable, aes(x = x, y = y, fill = factor(x))) + geom_tile() + scale_fill_manual(values = color)

mixcolorhcl <- function(first, second) {
  hex(mixcolor(alpha = 0.5, 
               color1 = hex2RGB(first), color2 = hex2RGB(second)))
}

mixcolor <- mixcolorhcl(color[1], color[10])
names(mixcolor) <- "1"
mixtable <- data.frame(x = 1, y = 1, fill = 1)
ggplot(mixtable, aes(x = x, y = y, fill = factor(fill))) + geom_tile() + scale_fill_manual(values = mixcolor)

```

### 3. 表格的制作
```{r}
#配置分析环境
library(stringr)

#导入实验数据
en_nv <- read.csv(file.choose(), header = T)
en_ihiy <- read.csv(file.choose(), header = T)

#对数据进行初步筛选与整理
en_nv <- select(en_nv, answer1.Block., sound111, sound112)
en_ihiy <- select(en_ihiy, answer1.SubTrial.,answer2.SubTrial.,starts_with("sound"))

names(en_nv)[1] <- "answer"
names(en_ihiy)[1] <- "answer"
names(en_ihiy)[2] <- "rate"

en_ihiy$rate <- stringr::str_sub(en_ihiy$rate, start = 2, end = -1)

#制作实验1的表格
en_nv <- unite(en_nv, sound, sound111, sound112)
en_ihiy <- unite(en_ihiy, col = sound, sound111, sound112, sound113, sound114, sound115, sound121, sound122, sound123, sound124, sound125)

#清除缺失值
en_nv <- na.omit(en_nv)
en_ihiy <- na.omit(en_ihiy)

#对数据中的文件路径含义进行修改

#将实验1的文件路径改为对应单词，并确认是否匹配
en_nv$sound <- str_extract(en_nv$sound, pattern = "(w|h).*d")
en_nv <- mutate(en_nv, match = sound == answer)
table(en_nv$match, en_nv$sound)

#复杂频数表
# ftable实现
ftable(en_nv, row.vars = c(1,3), col.vars = 2)


#将实验2的文件路径改为定位坐标
en_ihiy$sound <- str_extract(en_ihiy$sound, pattern = "F1_..-F2_..")
en_ihiy <- separate(en_ihiy, col = sound, into = c("X","Y"), sep = "-")
en_ihiy$X <- as.numeric(str_replace(en_ihiy$X, pattern = "F1_", replacement = ""))
en_ihiy$Y <- as.numeric(str_replace(en_ihiy$Y, pattern = "F2_", replacement = ""))

#对实验2中出现的单词数进行计数
summary(en_ihiy$answer)
```

### 4. 绘制 heed hid 的热力图
```{r}
data_en_ihiy <- reshape2::dcast(en_ihiy, X + Y ~ answer)

#选择出现频率最高的几个单词作为绘图依据
data_en_ihiy <- select(data_en_ihiy, X, Y, heed, hid)
data_en_ihiy[data_en_ihiy == 0] <- NA

#构造色彩映射
heed_color <- sequential_hcl(10, h = 60, c = c(100, 30), l = c(50, 90))
names(heed_color) <- factor(str_c("heed",10:1))
hid_color <- sequential_hcl(10, h = 240, c = c(100, 30), l = c(50, 90))
names(hid_color) <- factor(str_c("hid",10:1))
hood_color <- sequential_hcl(10, h = 190, c = c(100, 30), l = c(50, 90))
names(hood_color) <- factor(str_c("hood",10:1))
heard_color <- sequential_hcl(10, h = 280, c = c(100, 30), l = c(50, 90))
names(heard_color) <- factor(str_c("heard",10:1))
color_total <- c(heed_color, hid_color)

#制作绘图参考值的表格
data_en_ihiy <- mutate(data_en_ihiy, heedcolor = heed, hidcolor = hid)
data_en_ihiy$heedcolor <- str_c("heed", data_en_ihiy$heedcolor)
data_en_ihiy$hidcolor <- str_c("hid", data_en_ihiy$hidcolor)
#data_en_ihiy$hoodcolor <- str_c("hood", data_en_ihiy$hoodcolor)
#data_en_ihiy$heardcolor <- str_c("heard", data_en_ihiy$headcolor)

#统计是否需要颜色混合
count <- vector()
for(i in 1:nrow(data_en_ihiy)){
  count[i] <- sum(is.na(data_en_ihiy[i,3:4]) == FALSE)
}

data_en_ihiy <- cbind(data_en_ihiy, count)


#建立整合色彩函数
select_one_color <- function(x){
  a <- select(x, heedcolor, hidcolor)
  b <- a[which(is.na(a) == FALSE)]
  return(color_total[[b[[1]]]])
}

mix_two_color <- function(x){
  a <- select(x, heedcolor, hidcolor)
  b <- a[which(is.na(a) == FALSE)]
  c <- mixcolorhcl(color_total[[b[[1]]]], color_total[[b[[2]]]])
  return(c)
}

mix_three_color <- function(x){
  a <- select(x, heedcolor, hidcolor)
  b <- a[which(is.na(a) == FALSE)]
  c <- mixcolorhcl(color_total[[b[[1]]]], color_total[[b[[2]]]])
  d <- mixcolorhcl(c, color_total[[b[[3]]]])
  return(d)
}

mix_four_color <- function(x){
  a <- select(x, heedcolor, hidcolor, hoodcolor, headcolor)
  b <- a[which(is.na(a) == FALSE)]
  c <- mixcolorhcl(color_total[[b[[1]]]], color_total[[b[[2]]]])
  d <- mixcolorhcl(color_total[[b[[4]]]], color_total[[b[[3]]]])
  e <- mixcolorhcl(c,d)
  return(e)
}
  
#构建色彩映射向量  
color_map <- vector()
data_en_ihiy <- filter(data_en_ihiy, count > 0)
for(i in 1 : nrow(data_en_ihiy)){
  z <- data_en_ihiy[i,]
  color_map[i] <- switch(z$count,
    select_one_color(z),
    mix_two_color(z)
  )
}

names(color_map) <- as.character(1:nrow(data_en_ihiy))

#构造填字内容列（如果要改单词，需要把下面的三个*_table的赋值都进行修改）
temp_table <- select(data_en_ihiy,heed, hid) #用于比较大小的表格
cheak_table <- select(data_en_ihiy, X,Y, heed, hid) #用于选择相应比例值的表格
rate_map <- vector()

temp_table[is.na(temp_table)] <- 0

for(i in 1 : nrow(temp_table)){
 char_num <- which(temp_table[i,] == max(temp_table[i,]))
 
 x <- cheak_table[i, ]$X
 y <- cheak_table[i, ]$Y
 
 get_rate_table <- en_ihiy %>% 
  filter(X == x, Y == y, answer == "heed"|answer=="hid") %>%  #记得这里也要修改
  group_by(answer) %>%
  summarise(mean(as.numeric(rate)))
 judge_name <- names(temp_table)
 
 if(length(char_num) != 1){
  rate_map[i] <- max(get_rate_table$`mean(as.numeric(rate))`)
}else{
  get_rate <- get_rate_table %>% 
   filter(answer == judge_name[char_num])
  rate_map[i] <- get_rate[[2]]
  }
}

rate_map <- as.character(round(rate_map,digits = 1))

data_en_ihiy <- cbind(data_en_ihiy, rate_map)

position <- c(1:nrow(data_en_ihiy))
data_en_ihiy <- cbind(data_en_ihiy, position)

figure_without_text <- ggplot(data_en_ihiy, aes(x = X, y = Y, fill = as.factor(position))) + geom_tile(show.legend = F) + scale_fill_manual(values = color_map) + theme_bw() + coord_equal(ratio = 1)

figure_with_text <- ggplot(data_en_ihiy, aes(x = X, y = Y, fill = as.factor(position))) + geom_tile(show.legend = F) + scale_fill_manual(values = color_map) + theme_bw() + geom_text(aes(label = rate_map)) + coord_equal(ratio = 1)

ggsave("figure_with_text.pdf", plot = figure_with_text, dpi = 300, width = 10)
ggsave("figure_without_text.pdf", plot = figure_without_text, dpi = 300, width = 10)

ggplot(data_en_ihiy, aes(x = X, y = Y, fill = as.factor(position))) + geom_tile(show.legend = F) + scale_fill_manual(values = color_map) + theme_bw() + coord_equal(ratio = 1)

ggplot(data_en_ihiy, aes(x = X, y = Y, fill = as.factor(position))) + geom_tile(show.legend = F) + scale_fill_manual(values = color_map) + theme_bw() + geom_text(aes(label = rate_map)) + coord_equal(ratio = 1)
```

### 5. 绘制 hood heard 的热力图
```{r}
data_en_ihiy <- reshape2::dcast(en_ihiy, X + Y ~ answer)

#选择出现频率最高的几个单词作为绘图依据
data_en_ihiy <- select(data_en_ihiy, X, Y, hood, heard)
data_en_ihiy[data_en_ihiy == 0] <- NA

#构造色彩映射
hood_color <- sequential_hcl(10, h = 190, c = c(100, 30), l = c(50, 90))
names(hood_color) <- factor(str_c("hood",10:1))
head_color <- sequential_hcl(10, h = 280, c = c(100, 30), l = c(50, 90))
names(heard_color) <- factor(str_c("heard",10:1))
color_total <- c(hood_color, heard_color)

#制作绘图参考值的表格
data_en_ihiy <- mutate(data_en_ihiy, hoodcolor = hood, heardcolor = heard)
data_en_ihiy$hoodcolor <- str_c("hood", data_en_ihiy$hoodcolor)
data_en_ihiy$heardcolor <- str_c("heard", data_en_ihiy$heardcolor)

#统计是否需要颜色混合
count <- vector()
for(i in 1:nrow(data_en_ihiy)){
  count[i] <- sum(is.na(data_en_ihiy[i,3:4]) == FALSE)
}

data_en_ihiy <- cbind(data_en_ihiy, count)


#建立整合色彩函数
select_one_color <- function(x){
  a <- select(x, hoodcolor, heardcolor)
  b <- a[which(is.na(a) == FALSE)]
  return(color_total[[b[[1]]]])
}

mix_two_color <- function(x){
  a <- select(x, hoodcolor, heardcolor)
  b <- a[which(is.na(a) == FALSE)]
  c <- mixcolorhcl(color_total[[b[[1]]]], color_total[[b[[2]]]])
  return(c)
}

mix_three_color <- function(x){
  a <- select(x, heedcolor, hidcolor)
  b <- a[which(is.na(a) == FALSE)]
  c <- mixcolorhcl(color_total[[b[[1]]]], color_total[[b[[2]]]])
  d <- mixcolorhcl(c, color_total[[b[[3]]]])
  return(d)
}

mix_four_color <- function(x){
  a <- select(x, heedcolor, hidcolor, hoodcolor, headcolor)
  b <- a[which(is.na(a) == FALSE)]
  c <- mixcolorhcl(color_total[[b[[1]]]], color_total[[b[[2]]]])
  d <- mixcolorhcl(color_total[[b[[4]]]], color_total[[b[[3]]]])
  e <- mixcolorhcl(c,d)
  return(e)
}
  
#构建色彩映射向量  
color_map <- vector()
data_en_ihiy <- filter(data_en_ihiy, count > 0)
for(i in 1 : nrow(data_en_ihiy)){
  z <- data_en_ihiy[i,]
  color_map[i] <- switch(z$count,
    select_one_color(z),
    mix_two_color(z)
  )
}

names(color_map) <- as.character(1:nrow(data_en_ihiy))

#构造填字内容列（如果要改单词，需要把下面的三个*_table的赋值都进行修改）
temp_table <- select(data_en_ihiy,hood, heard) #用于比较大小的表格
cheak_table <- select(data_en_ihiy, X,Y, hood, heard) #用于选择相应比例值的表格
rate_map <- vector()

temp_table[is.na(temp_table)] <- 0

for(i in 1 : nrow(temp_table)){
 char_num <- which(temp_table[i,] == max(temp_table[i,]))
 
 x <- cheak_table[i, ]$X
 y <- cheak_table[i, ]$Y
 
 get_rate_table <- en_ihiy %>% 
  filter(X == x, Y == y, answer == "hood"|answer=="heard") %>%  #记得这里也要修改
  group_by(answer) %>%
  summarise(mean(as.numeric(rate)))
 judge_name <- names(temp_table)
 
 if(length(char_num) != 1){
  rate_map[i] <- max(get_rate_table$`mean(as.numeric(rate))`)
}else{
  get_rate <- get_rate_table %>% 
   filter(answer == judge_name[char_num])
  rate_map[i] <- get_rate[[2]]
  }
}

rate_map <- as.character(round(rate_map,digits = 1))

data_en_ihiy <- cbind(data_en_ihiy, rate_map)

position <- c(1:nrow(data_en_ihiy))
data_en_ihiy <- cbind(data_en_ihiy, position)

figure_without_text <- ggplot(data_en_ihiy, aes(x = X, y = Y, fill = as.factor(position))) + geom_tile(show.legend = F) + scale_fill_manual(values = color_map) + theme_bw() + coord_equal(ratio = 1)

#figure_with_text <- ggplot(data_en_ihiy, aes(x = X, y = Y, fill = as.factor(position))) + geom_tile(show.legend = F) + scale_fill_manual(values = color_map) + theme_bw() + geom_text(aes(label = rate_map)) + coord_equal(ratio = 1)

#ggsave("hood_figure_with_text.png", plot = figure_with_text, dpi = 300, width = 10)
ggsave("hood_figure_without_text.png", plot = figure_without_text, dpi = 300, width = 10)

ggplot(data_en_ihiy, aes(x = X, y = Y, fill = as.factor(position))) + geom_tile(show.legend = F) + scale_fill_manual(values = color_map) + theme_bw() + coord_equal(ratio = 1)

#ggplot(data_en_ihiy, aes(x = X, y = Y, fill = as.factor(position))) + geom_tile(show.legend = F) + scale_fill_manual(values = color_map) + theme_bw() + geom_text(aes(label = rate_map)) + coord_equal(ratio = 1)
```

